services:
  app:

    container_name: auth_service_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - msa-net


networks:
  msa-net:
    external: true
