services:
  auth-service:

    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - msa-net
    environment:
      - TZ: Asia/Seoul


networks:
  msa-net:
    external: true
