jwt:
  secret: ${JWT_SECRET_KEY}

server:
  port: 8081

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_USER}
  secret-key: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}

spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

