services:
  user-db:
    image: postgres
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"  # 로컬에서 접근할 포트
    restart: always
    networks:
      - msa-net
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  auth-data:

networks:
  msa-net:
    external: true

